---
title: "Validación de pedodiversidad taxonómica"
output: github_document
---

## 1. Configuración

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Carga

Se cargan los datos de SoilGrids


```{r cars}

descargar_soilgrids_stack <- function(vars = c("sand", "silt", "soc", "cec"),
                                      depth = "0-5cm",
                                      stat = "mean",
                                      crs_salida = "EPSG:9377",
                                      resolucion = c(250, 250)) {
    if (!"pacman" %in% installed.packages()[, "Package"]) install.packages("pacman")
    pacman::p_load("terra", "gdalUtilities", "sf")

    # Bounding box en IGH para Colombia
    bb <- c(-8800000.000, 1400000.000, -7400000.000, -500000.000)
    igh <- "+proj=igh +lat_0=0 +lon_0=0 +datum=WGS84 +units=m +no_defs"
    sg_url <- "/vsicurl?max_retry=3&retry_delay=1&list_dir=no&url=https://files.isric.org/soilgrids/latest/data/"

    capas <- list()

    for (v in vars) {
        capa <- paste0(v, "_", depth, "_", stat)
        vrt_remote <- paste0(sg_url, v, "/", capa, ".vrt")
        vrt_local <- file.path(tempdir(), paste0(capa, ".vrt"))

        # Descargar VRT recortado
        gdal_translate(
            vrt_remote,
            vrt_local,
            of = "VRT",
            tr = resolucion,
            projwin = bb,
            projwin_srs = igh
        )

        # Leer y reproyectar a EPSG 9377
        r <- terra::rast(vrt_local)
        r_proj <- terra::project(r, crs_salida)
        names(r_proj) <- v
        capas[[v]] <- r_proj
    }

    # Stack de todas las capas reproyectadas
    return(terra::rast(capas))
}

stack_suelos <- descargar_soilgrids_stack()
plot(stack_suelos)


```

## Including Plots

